# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='monitoring_board.Contact'),
        ),
    ]
