# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_board', '0003_auto_20171209_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
